apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-movies
  title: My Movies React
  description: Interface web em React para [descreva o produto].
  tags:
    - react
    - typescript
    - frontend
spec:
  type: website
  lifecycle: production
  owner: group:default/squad-super-rag
  domain: domain:default/claro-ia-corporativa
